---
run-name: Linting the code
name: Build and test
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install Dependencies
        run: yarn install
      - name: Lint the project
        run: yarn lint
      - name: Echo
        run: echo "This job's status is ${{ job.status }}."
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: jimmy9877/webapp:latest
